### ISSUE TITLE
Gazebo pkgs on ros2 Humble

### ISSUE THREAD

**Issue by oscarlov** [AdrianCobo/my_bot#19]
Hi, I'm trying to install the same pkgs of you, but when i try to launch sudo apt-get install ros-humble-gazebo-ros-pkgs and all the others it return to me "E: Unable to locate package ros-humble-gazebo-ros-pkgs". Same thing for ros-humble-gazebo-ros2-control. I'm using ros2 Humble on an Ubuntu 22.04 on a Raspberry PI 4B. How did you resolve this problem?

**Comment by AdrianCobo** [comment]
Do you have ROS2 correctly installed? 

[tutorial](https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html)

It seems to me that the Ubuntu Universe repository is not enabled
